### ISSUE TITLE
actix-connect : use of unstable library feature 'copied'

### ISSUE THREAD

**Issue by dessalines** [actix/actix-net#32]
I'm doing a build using `actix-web 1.0.5` and `actix 0.8.3` and getting the following error when the dependencies are compiling for `cargo build --release`

This is from a docker image `rust:latest` or `1.36`

```
error[E0658]: use of unstable library feature 'copied' (see issue #57126)
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-connect-0.2.1/src/connect.rs:152:56
```

**Comment by fafhrd91** [comment]
@mitsuhiko could you check, it is from last Pr

**Comment by mitsuhiko** [comment]
copied is new in 1.36. If we want to support older rusts we can change it to cloned.

**Comment by mitsuhiko** [comment]
Fatfingered closed issue.

**Comment by fafhrd91** [comment]
I am fine with latest stable. @dessalines are you sure you use 1.36?

**Comment by dessalines** [comment]
I'll try repulling it, rebuilding and report back.

**Comment by dessalines** [comment]
Apologize for wasting yall's time, looks like I'm never using docker's `latest` tag again, since it's usually not the latest. I repulled `1.36` and it worked fine.

**Comment by 0xpr03** [comment]
@mitsuhiko this is a breaking change. The readme state "Minimum supported Rust version: 1.32 or later" !

**Comment by 0xpr03** [comment]
We should at least update the readme to reflect this, the damage is already done.
